// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdB_JVKZr1Ehvo1GCCq6-UEPuZPqwsNVE',
    appId: '1:116317517472:web:263b3d226ba461a1423bc5',
    messagingSenderId: '116317517472',
    projectId: 'expensly-76411',
    authDomain: 'expensly-76411.firebaseapp.com',
    storageBucket: 'expensly-76411.firebasestorage.app',
    measurementId: 'G-K43T6B0VEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ2yi7YU4CXfhum1LvMFU_KSzS9Hrmf9g',
    appId: '1:116317517472:android:6e3f7214bf4fc2ce423bc5',
    messagingSenderId: '116317517472',
    projectId: 'expensly-76411',
    storageBucket: 'expensly-76411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChw1oceZ8J8e2FC5uL3ZQGIege03irkzI',
    appId: '1:116317517472:ios:c4e19106c3bfe35c423bc5',
    messagingSenderId: '116317517472',
    projectId: 'expensly-76411',
    storageBucket: 'expensly-76411.firebasestorage.app',
    iosClientId: '116317517472-j8367cfsvl367sqcip1c30k7ad22ler3.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChw1oceZ8J8e2FC5uL3ZQGIege03irkzI',
    appId: '1:116317517472:ios:c4e19106c3bfe35c423bc5',
    messagingSenderId: '116317517472',
    projectId: 'expensly-76411',
    storageBucket: 'expensly-76411.firebasestorage.app',
    iosClientId: '116317517472-j8367cfsvl367sqcip1c30k7ad22ler3.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdB_JVKZr1Ehvo1GCCq6-UEPuZPqwsNVE',
    appId: '1:116317517472:web:b199b78a12352029423bc5',
    messagingSenderId: '116317517472',
    projectId: 'expensly-76411',
    authDomain: 'expensly-76411.firebaseapp.com',
    storageBucket: 'expensly-76411.firebasestorage.app',
    measurementId: 'G-37QG0CMJKB',
  );
}
